deathMsg="WARNING: YOU HAVE BEEN DETECTED ATTEMPTING TO ACCESS THE FILES ON THIS ARCHIVE WITHOUT OFFICIAL APRROVAL. MEMATIC KILL AGENT ACTIVATED. SAY YOUR LAST WORDS.";

console.log(deathMsg);

function spamYee() {
console.log('YEEEEEEEEEEEEEEEEEEEEEE')
}